# Use root/example as user/password credentials
version: '3.1'

services:
  pokemon-app:
    image: node:15.2.0-buster
    working_dir: /usr/src/app
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    ports:
      - 27017:27017
